---
title: "read SBE CTD cnv-files into data.frame"
author: "Marko Lipka, David Kaiser"
date: "12/2/2017"
output: github_document
---

*read.cnv.file()* function takes a filename of a .cnv file as argument and returns a data.frame.

```{r setup, include=FALSE}
library(knitr)
library(pander)
knitr::opts_chunk$set(echo = TRUE)
source("read.cnv.files.R")
source("plot.CTD.data.R")
```

#Example

```{r Examples}
Ex1 <- read.cnv.file("example data/V0001F01.cnv")
Ex2 <- read.cnv.file("example data/P0009F01.cnv")

pander(head(Ex1$data))
pander(Ex1$meta)

pander(head(Ex2$data))
pander(Ex2$meta)
```

## Plots

```{r, fig.width=12, fig.height=4}
plot.CTD.data(Ex1)
plot.CTD.data(Ex2)
```


```{r pressure, echo=FALSE, fig.width=12, fig.height=4, eval = F}
library("reshape2")
melted.df.1 <- melt(Ex1$data,
                  id.vars = c("depSM", "scan", "nbin",
                              "flag", "timeS", "nbf",
                              "altM", "prDM",
                              "header.latitude", "header.longitude"
                              ))

melted.df.2 <- melt(Ex2$data,
                  id.vars = c("depSM", "scan", "nbin",
                              "flag", "timeS", "nbf",
                              "altM", "prDM", "spar",
                              "header.latitude", "header.longitude",
                              "latitude", "longitude"
                              ))

library("ggplot2")
ggplot(melted.df.1,
       aes(x = depSM, y = value)) +
    geom_line() +
    scale_x_reverse() +
    coord_flip() +
    facet_grid(.~variable, scales = "free") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(melted.df.2,
       aes(x = depSM, y = value)) +
    geom_line() +
    scale_x_reverse() +
    coord_flip() +
    facet_grid(.~variable, scales = "free") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
